# API Contract
# 最後更新：YYYY-MM-DD
#
# 此文件定義所有 API 端點的規格
# 修改 API 必須先更新此文件

openapi: 3.0.0
info:
  title: Project API
  version: 1.0.0
  description: API documentation for the project

servers:
  - url: http://localhost:3000
    description: Development server

paths:
  # ============================================
  # Health Check
  # ============================================
  /api/health:
    get:
      summary: Health check endpoint
      tags:
        - System
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time

  # ============================================
  # Example Resource
  # ============================================
  # /api/resources:
  #   get:
  #     summary: List all resources
  #     tags:
  #       - Resources
  #     parameters:
  #       - name: page
  #         in: query
  #         schema:
  #           type: integer
  #           default: 1
  #       - name: limit
  #         in: query
  #         schema:
  #           type: integer
  #           default: 10
  #     responses:
  #       '200':
  #         description: List of resources
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 data:
  #                   type: array
  #                   items:
  #                     $ref: '#/components/schemas/Resource'
  #                 total:
  #                   type: integer
  #                 page:
  #                   type: integer
  #                 limit:
  #                   type: integer

components:
  schemas:
    # ============================================
    # Common Schemas
    # ============================================
    Error:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string

    # ============================================
    # Resource Schemas
    # ============================================
    # Resource:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #       format: uuid
    #     name:
    #       type: string
    #     createdAt:
    #       type: string
    #       format: date-time
    #     updatedAt:
    #       type: string
    #       format: date-time

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
